version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: postgres_de
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_de
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "6969:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: